// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ApiRepository.Weather;
//
//    var weather = Weather.FromJson(jsonString);

namespace LocationData.Core.Models.Weather
{
    using System.Collections.Generic;

    public interface IWeatherData
    {
        Coord Coord { get; set; }
        List<Weather> Weather { get; set; }
    }
}